### ISSUE TITLE
Docker instance fails to start

### ISSUE THREAD

**Issue by Raainman** [TobiasS1402/appieSniper#4]
Tried to start the docker container, with env settings and env-file. Both failed with the following error;

2022-10-03 13:49:30 INFO     Environment file has been read
Traceback (most recent call last):
  File "/appie/main.py", line 169, in <module>
    main()
  File "/appie/main.py", line 156, in main
    boxRequests()
  File "/appie/main.py", line 120, in boxRequests
    results = init(float(readConfig().get('latitude')),float(readConfig().get('longitude'))) #Don't forget to make this a variable / cli parameter
TypeError: float() argument must be a string or a number, not 'NoneType'

contens of my env-file; (telegram bottoken and chatid were left out)

longitude=5.708120
latitude=51.924280
telegram_bot_token='xxx'
telegram_chat_id='xxx'
number_of_stores=5 #nearby number of stores, based on API calculations with your longitude and latitude returned by the GraphQL endpoint

this was the docker run cmd;

docker run -d --name appiesniper --env-file ./.env -d ghcr.io/tobiass1402/appiesniper:v0.1.2

**Comment by TobiasS1402** [comment]
Hello @Raainman,

I think i figured it out, it had to do partly with unbuilt docker images and changes that were not built and the other part was the .env with this comment inside of it which did not play nice: _#nearby number of stores, based on API calculations with your longitude and latitude returned by the GraphQL endpoint_.

Could you try running the new container version _(v0.1.4)_ with your .env configuration without the comment? I also updated the `.env.example` file to make this clear.
` docker run --env-file .env -d ghcr.io/tobiass1402/appiesniper:v0.1.4`

```
longitude=5.708120
latitude=51.924280
telegram_bot_token='xxx'
telegram_chat_id='xxx'
number_of_stores=5
```

Kind regards,

**Comment by Raainman** [comment]
Ok, I have some improvement. The container is running now and telegram messages are coming in. However it does not seem the .env file is picked up. I see telegram messages from around arnhem (probably some default), even when I enter coordinates from Rotterdam. Also I see in the log this message;

2022-10-04T10:08:58.076756318Z 2022-10-04 10:08:58 INFO     .env file not present, falling back to normal Environment

This is the .env that I am now using;

longitude=4.477733
latitude=51.924419
telegram_bot_token=9999:999
telegram_chat_id=9999
number_of_stores=100

This is the command I used;

**Comment by Raainman** [comment]
Works fine now, thanks!
